// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bzgkevlaejzycdmeqxon.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ6Z2tldmxhZWp6eWNkbWVxeG9uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMTU1MTEsImV4cCI6MjA2MzU5MTUxMX0.UcxPdrIXTRGp08ODLXjK9i9KxGHZynsv_XRrbJkMuZk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});